# Generated by Django 3.2.25 on 2025-08-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
