# Generated by Django 3.2.25 on 2025-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comment_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='filetype',
            field=models.CharField(default='', max_length=255),
        ),
    ]
